// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ludoxpxvfxyfiggpwsch.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx1ZG94cHh2Znh5ZmlnZ3B3c2NoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4ODg4NDEsImV4cCI6MjA3MjQ2NDg0MX0.5Sg8jU_QamPRatBKp2cnplmOvg3CRj1sPLq9LJQPQS8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});